name: boilerplate_postgresql
description: Boilerplate for using postgresql with Jaguar.dart
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  postgresql: '>=0.3.4+1 <0.4.0'
  jaguar: '>=0.5.3 <0.6.0'
  jaguar_postgresql: '>=0.5.0 <0.6.0'
  jaguar_serializer: '>=0.3.4 <0.4.0'
  jaguar_reflect: '>=0.5.1 <0.6.0'
  http: any
  jaguar_query: ^0.0.22
  jaguar_orm: ^0.1.3
  jaguar_query_postgresql: ^0.0.4
  ulid: ^1.0.0

dev_dependencies:
  test: