name: tasks_common
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Issac <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  jaguar_serializer: ^2.1.8
  jaguar_common: ^2.1.1
  jaguar_resty: ^2.6.1

dev_dependencies:
  jaguar_serializer_cli: ^2.1.24
  test: ^1.0.0
  build_runner: ^0.9.0
