name: dart_html
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Issac <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  tasks_common:
    path: ../../tasks_common

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
